services:

  broker:
    container_name: tg_broker
    build:
      context: ./services/broker
      dockerfile: Dockerfile
    working_dir: /go/src/taskProvider
    depends_on:
      - user
    volumes:
      - ./services/broker:/go/src/taskProvider/services/broker
    restart: always
    ports:
      - "5040:5040"
    dns_search: .
    #environment:
      #- GRPC_GO_LOG_VERBOSITY_LEVEL=99 
      #- GRPC_GO_LOG_SEVERITY_LEVEL=info

  user:
    container_name: tg_user
    build:
      context: ./services/user
      dockerfile: Dockerfile
    working_dir: /go/src/taskProvider
    volumes:
      - ./services/user:/go/src/taskProvider/services/user
    restart: always
    ports:
      - "5041:5041"

  getway:
    container_name: tg_getway
    build:
      context: ./services/getway
      dockerfile: Dockerfile
    working_dir: /go/src/taskProvider
    depends_on:
      - user
    volumes:
      - ./services/getway:/go/src/taskProvider/services/getway
    restart: always
    ports:
      - "8081:8081"
    environment:
      - GRPC_TRACE=all
      - GRPC_VERBOSITY=DEBUG
      - GRPC_GO_LOG_VERBOSITY_LEVEL=2
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      


