version: "3.8"
services:
  broker:
    container_name: tg_broker
    build:
      context: ./services/broker
      dockerfile: Dockerfile
    working_dir: /go/src/taskProvider
    volumes:
      - ./services/broker:/go/src/taskProvider/services/broker
    restart: always
    environment:
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99 
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
    networks:
      static-network:
        ipv4_address: 172.16.238.2

  user:
    container_name: tg_user
    build:
      context: ./services/user
      dockerfile: Dockerfile
    working_dir: /go/src/taskProvider
    volumes:
      - ./services/user:/go/src/taskProvider/services/user
    restart: always
    networks:
      static-network:
        ipv4_address: 172.16.238.3 

  getway:
    container_name: tg_getway
    build:
      context: ./services/getway
      dockerfile: Dockerfile
    working_dir: /go/src/taskProvider
    volumes:
      - ./services/getway:/go/src/taskProvider/services/getway
    restart: always
    ports:
      - "8081:8081"
    environment:
      - GRPC_TRACE=all
      - GRPC_VERBOSITY=DEBUG
      - GRPC_GO_LOG_VERBOSITY_LEVEL=2
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
    networks:
      static-network:
        ipv4_address: 172.16.238.4
  


networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"